/** @type {import('tailwindcss').Config} */
export default {
        content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        ],
        theme: {
        extend: {},
        },
        plugins: [],
        safelist: [
            'animate-fall',
            'text-3xl',
            'text-4xl',
            'sm:text-4xl',
            'sm:text-5xl',
            'md:text-5xl',
            'md:text-6xl',
            'lg:text-6xl',
            'lg:text-7xl',
            'text-lg',
            'text-xl',
            'sm:text-xl',
            'sm:text-2xl',
            'md:text-2xl',
            'md:text-3xl',
            'absolute',
            'top-0',
            'z-0',
            'min-h-screen',
            'bg-neutral-900',
            'flex',
            'flex-col',
            'overflow-hidden',
            'relative',
            'inset-0',
            'bg-transparent',
            'text-white',
            'z-10',
            'justify-evenly',
            'px-4',
            'sm:px-8',
            'text-center',
            'break-words',
            'max-w-[90vw]',
            'font-concertone',
            'items-center',
            'gap-3',
            'gap-4',
            'gap-5',
            'sm:gap-5',
            'sm:gap-6',
            'max-w-md',
            'max-w-lg'
        ],
    };
